# Generated by Django 5.2.6 on 2025-09-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='price',
        ),
    ]
